name: audio_waveforms
description: A Flutter package that allow you to generate waveform while recording audio or from audio file. Fork of SimformSolutionsPvtLtd/audio_waveforms, modernised for AGP 9, AndroidX Media3 and Swift Package Manager.
version: 2.0.3
homepage: https://github.com/ChristopherCfly/audio_waveforms
repository: https://github.com/ChristopherCfly/audio_waveforms
issue_tracker: https://github.com/ChristopherCfly/audio_waveforms/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


flutter:
  plugin:
    platforms:
      android:
        package: com.simform.audio_waveforms
        pluginClass: AudioWaveformsPlugin
      ios:
        pluginClass: AudioWaveformsPlugin
      macos:
        pluginClass: AudioWaveformsPlugin

