plugins {
    id "com.android.library"
    id "org.jetbrains.kotlin.android"
}

group = 'com.simform.audio_waveforms'
version = '1.0-SNAPSHOT'

android {
    namespace "com.simform.audio_waveforms"

    compileSdk 37

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = '17'
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        minSdk 24
    }
}

dependencies {
    implementation "androidx.media3:media3-exoplayer:1.11.1"
    implementation "androidx.media3:media3-common:1.11.1"
}
