plugins {
    id "com.android.library"
    id "org.jetbrains.kotlin.android"
}

group = 'com.simform.audio_waveforms'
version = '1.0-SNAPSHOT'

android {
    namespace "com.simform.audio_waveforms"

    compileSdk 37

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = '17'
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        minSdk 24
    }
}

dependencies {
    implementation("androidx.multidex:multidex:2.0.1")
    implementation "com.google.android.exoplayer:exoplayer:2.17.1"
}
